In [3]:
import numpy as np

matrix_A = np.array([
    [1, 2, 4],
    [7, 5, -2],
    [-2, 1, 3]
])

matrix_B = np.array([
    [-1, 0, 3],
    [2, -6, 1],
    [-7, 1, 5]
])

matrix_C = np.array([
    [-2, 3],
    [4, 0],
    [7, -1]
])

print(matrix_A + matrix_B)

[[ 0  2  7]
 [ 9 -1 -1]
 [-9  2  8]]


In [5]:
print(matrix_B - matrix_A)

[[ -2  -2  -1]
 [ -5 -11   3]
 [ -5   0   2]]


In [6]:
print(np.dot(matrix_A, matrix_B))

[[-25  -8  25]
 [ 17 -32  16]
 [-17  -3  10]]


In [10]:
print(matrix_A @ matrix_B @ matrix_C)

[[ 193 -100]
 [ -50   35]
 [  92  -61]]


In [12]:
matrix_A = np.array([
    [0, 3, 4],
    [-7, 1, -2],
    [2, -1, 3]
])

matrix_B = np.array([
    [1, 2, 4],
    [7, 0, -2],
    [-3, -2, 5]
])

matrix_C = np.array([
    [-3, 2],
    [0, 4],
    [-1, 7]
])
print('+' * 20)
print(matrix_A + matrix_B)
print('+' * 20)
print(matrix_B - matrix_A)
print('+' * 20)
print(np.dot(matrix_A, matrix_B))
print('+' * 20)
print(matrix_A @ matrix_B @ matrix_C)
print('+' * 20)

++++++++++++++++++++
[[ 1  5  8]
 [ 0  1 -4]
 [-1 -3  8]]
++++++++++++++++++++
[[ 1 -1  0]
 [14 -1  0]
 [-5 -1  2]]
++++++++++++++++++++
[[  9  -8  14]
 [  6 -10 -40]
 [-14  -2  25]]
++++++++++++++++++++
[[ -41   84]
 [  22 -308]
 [  17  139]]
++++++++++++++++++++
